# Generated by Django 4.2.3 on 2023-07-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='audited',
            field=models.BooleanField(default=False),
        ),
    ]
